### PR TITLE
[WIP] badge42 ver2

### LINKED ISSUE #64: [Suggestion] Preserve user data against update 42seoul Policy for outer circle
Outer circles can no longer receive 42API information after February. 

I would like to preserve information about this.

### LINKED ISSUE #66: Addition of certification procedures to satisfy the EU GDPR policy.
- #67

### PR DESCRIPTION
**Pull request by JaeSeoKim**
> ### 🚧 work in progress ...

### 📌 TODO

- [x] Auth System
- [x] Stats Badge
- [x] Project Badge
- [x] Create a previous API deprecated guide

### 🛠 Stack

- Framework - [Next.js v12](https://nextjs.org/)
- Language - [TypeScript](https://www.typescriptlang.org/)
- Auth - [NextAuth.js](https://next-auth.js.org/)
- Database - [PlanetScale](https://planetscale.com/)
- ORM - [Prisma](https://prisma.io/)
- Hosting - [Vercel](https://vercel.com/)
- Styling - [TailwindCSS](https://tailwindcss.com/)

### CODE REVIEW

**Comment by GlaceCoding** [comment]
It is a very great work !

For the user interface :

In `/me` page, you might add a "Edit badge link" to got back to `/` because when we login/register we go to `/me` page, and it is not obvious how to edit our badge, I randomly remove `me` in the browserbar to go back at the root page (`/`).

(Also on my badge I got my pool background, instead of 42 background and the level is wrong I got 5.17 instead of 4.2)

**EDIT :**
Also when we are already sign in, maybe redirect the user in this page : `/auth/signin?callbackUrl=https://badge42.vercel.app/me&error=SessionRequired`

**Comment by JaeSeoKim** [comment]
> It is a very great work !
> 
> For the user interface :
> 
> In `/me` page, you might add a "Edit badge link" to got back to `/` because when we login/register we go to `/me` page, and it is not obvious how to edit our badge, I randomly remove `me` in the browserbar to go back at the root page (`/`).
> 
> (Also on my badge I got my pool background, instead of 42 background and the level is wrong I got 5.17 instead of 4.2)
> 
> **EDIT :** Also when we are already sign in, maybe redirect the user in this page : `/auth/signin?callbackUrl=https://badge42.vercel.app/me&error=SessionRequired`

Thank you for your good opinion!
Could you tell me the url that is working incorrectly?

**Comment by JaeSeoKim** [comment]
@GlaceCoding 

When SVG is changed in Safari browser, there is an error in re-rendering strangely...

I don't like Safari browser. 🥲

**Comment by GlaceCoding** [comment]
> @GlaceCoding 
> 
> When SVG is changed in Safari browser, there is an error in re-rendering strangely...
> 
> I don't like Safari browser. 🥲

I forget to tell you my config it was on Firefox/Windows, but it is maybe the same problem

**Comment by GlaceCoding** [comment]
> Thank you for your good opinion! Could you tell me the url that is working incorrectly?

It works fine but the UI integration could be improved :)

When I retry to visit a new time your website, my browser suggest me this page : https://badge42.vercel.app/auth/signin?callbackUrl=https://badge42.vercel.app/me&error=SessionRequired I got this: 

image

It is fine, but I am already connected, you should make a HTML redirection when the user is already connected (the redirection should also rewrite the browser history if i'm not wrong)

**Comment by JaeSeoKim** [comment]
@GlaceCoding

- https://github.com/JaeSeoKim/badge42/pull/67#issuecomment-1073214593

I'll take it back, I don't like cross-browsing. 😂
Anyway, it will work normally now.

- https://github.com/JaeSeoKim/badge42/pull/67#issuecomment-1073221711

I am aware of this problem. This seems to be caused by adding an additional authentication system along with next-auth.

**Review by raccoman — CHANGES_REQUESTED** [review]
.

**Review by raccoman — APPROVED** [review]
I noticed that for coalitions that have a light color, always using white for the text doesn't create the right contrast.

**Comment by JaeSeoKim** [comment]
- #68

**Comment by JaeSeoKim** [comment]
@all-contributors please add @raccoman for review

**Comment by JaeSeoKim** [comment]
@all-contributors please add @GlaceCoding  for review ideas

**Pull request merged**
